public enum ScreenType
{
    MainMenu,
    GameUI,
    EndScreen,
    PlayScreen,
    DeckScreen,
    ShopScreen,
    EventsScreen,
    PremiumPassScreen,
    SettingsScreen,
    MessagesScreen,
    FriendsScreen,
    ProfileScreen,
    LoginScreen,
    RegisterScreen,
    MpLobbyScreen,
    Mod1,
    ChangeName,
    Mail,
    Friends,
    ProfileIcon
}